<<<<<<< Updated upstream
=======
<<<<<<< Updated upstream
include:
  - backend/docker-compose.yaml
=======
>>>>>>> Stashed changes
services:
  db:
    container_name: task_manager_backend_db
    image: mysql:8.4
    platform: linux/amd64
<<<<<<< Updated upstream
=======
    environment:
      MYSQL_NATIVE_PASSWORD: true
>>>>>>> Stashed changes
    env_file: backend/.env
    networks:
      - app_network
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
  backend:
    container_name: task_manager_backend
    build:
      context: ./backend
      dockerfile: dev.Dockerfile
    platform: linux/amd64
<<<<<<< Updated upstream

=======
>>>>>>> Stashed changes
    env_file: backend/.env
    networks:
      - app_network
    depends_on:
      - db
    ports:
      - "8000:8000"
    entrypoint: [".docker/entrypoint.dev.sh"]
<<<<<<< Updated upstream

  frontend:
    container_name: task_manager_frontend
    build:
      context: ./frontend
      dockerfile: dev.Dockerfile
    platform: linux/amd64
    env_file: frontend/.env
    networks:
      - app_network
    ports:
      - "3001:3000"
    command: yarn serve
=======
#   frontend:
#     container_name: task_manager_frontend
#     depends_on:
#       - backend
#     build:
#       context: ./frontend
#       dockerfile: dev.Dockerfile
#     platform: linux/amd64
#     env_file: frontend/.env
#     networks:
#       - app_network
#     ports:
#       - "3000:3000"
#     command: ["tail", "-f", "/dev/null"]
>>>>>>> Stashed changes

networks:
  app_network:
    driver: bridge

volumes:
  mysql_data:
<<<<<<< Updated upstream
=======
>>>>>>> Stashed changes
>>>>>>> Stashed changes
