# Generated by Django 5.2.4 on 2025-08-10 22:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmodel',
            name='uuid_id',
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),
    ]
