# Generated by Django 5.2.4 on 2025-08-10 22:45
import uuid

from django.db import migrations

def gen_uuid(apps, schema_editor):
    TaskModel = apps.get_model('tasks', 'TaskModel')
    for row in TaskModel.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=['uuid_id'])



class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_taskmodel_uuid_id'),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
