# Generated by Django 5.2.4 on 2025-08-10 22:45
import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_taskmodel_populated_uuid_id_values'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='uuid_id',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
