# Generated by Django 5.2.4 on 2025-08-10 22:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_taskmodel_remove_uuid_id_null'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskmodel',
            name='id',
        ),
        migrations.AlterField(
            model_name='taskmodel',
            name='uuid_id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
