# Generated by Django 5.2.4 on 2025-08-10 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_remove_taskmodel_id_alter_taskmodel_uuid_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskmodel',
            old_name='uuid_id',
            new_name='id',
        ),
    ]
