/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Task: typeof import('./components/Task.vue')['default']
    TaskManager: typeof import('./components/TaskManager.vue')['default']
    TasksList: typeof import('./components/TasksList.vue')['default']
  }
}
